Demonstration of a weird race condition in pipenv: if your Pipfile.lock
specifies a different version of setuptools than your system has installed,
*and* you go onto actually try to build a package, you can end up in a
situation where that package build fails because setuptools files are
disappearing out from underneath it.

Bizarrely, this results in `pipenv install` exiting 0 (no error), but a package
you'd expect to have installed is NOT INSTALLED. In the example, we expect a
package called `jfly` (which provides a `jfly.BadMath` module we hope to be
able to import) to be installed, but it doesn't always get installed.

To reproduce the issue:

    $ docker run $(docker build -q .)
    ...
    ****************************
    Resetting...
    Installing deps with pipenv...
    Successfully imported jfly.BadMath! <module 'jfly.BadMath' from '/usr/local/lib/python3.8/dist-packages/jfly/BadMath.py'>
    ****************************
    Runs: 37
    Successes: 3
    Failures: 34
    ****************************
    Resetting...
    Installing deps with pipenv...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'jfly'
    ****************************
    Runs: 38
    Successes: 3
    Failures: 35
    ****************************

To get more information, try passing `--verbose`:

    $ docker run $(docker build -q .) --verbose

You'll see evidence of setuptools getting uninstalled and re-installed:

    Installing collected packages: setuptools
      Attempting uninstall: setuptools
        Found existing installation: setuptools 45.2.0
        Uninstalling setuptools-45.2.0:
          Removing file or directory /usr/local/bin/easy_install
          Removing file or directory /usr/local/bin/easy_install-3.8
          Removing file or directory /usr/local/lib/python3.8/dist-packages/__pycache__/easy_install.cpython-38.pyc
          Removing file or directory /usr/local/lib/python3.8/dist-packages/easy_install.py
          Removing file or directory /usr/local/lib/python3.8/dist-packages/pkg_resources/
          Removing file or directory /usr/local/lib/python3.8/dist-packages/setuptools-45.2.0.dist-info/
          Removing file or directory /usr/local/lib/python3.8/dist-packages/setuptools/
          Successfully uninstalled setuptools-45.2.0
    Successfully installed setuptools-61.2.0

And you'll see errors like:

- `No module named 'setuptools.command.install'`
- `AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'`

It feels like there are 2 things going on here:

1. Speculation: Maybe there's a race condition where pipenv (indirectly) triggers this setuptools upgrade and simultaneously goes on to (inderectly) evaluate our package's setup.py file, which randomly fails to import things because the filesystem is in the process of changing.
2. Speculation: Maybe pipenv (or even pip) is invoking the setup.py in a way where it swallows errors? Or maybe there's some funky bug in setuptools itself? This sounds crazy, but I can't think of a better explanation for why pipenv itself exits successfully.

Notes:

This works if you use `pipenv install --sequential`

    ```
    Start of jfly-package/setup.py.
    Ancestor processes:
    stress,1 ./stress ./repro.sh --verbose
      `-bash,55 ./repro.sh --verbose
          `-pipenv,65 /usr/local/bin/pipenv install --system --deploy --verbose
              |-python3,84 -m pip install --verbose --upgrade --no-deps --exists-action=i -r /tmp/pipenv-g3j6zuvm-requirements/pipenv-gh97eywe-requirement.txt -i https://pypi.org/simple
              |   `-python3,98 -u -c \012exec(compile('''\012# This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py\012#\012# - It imports setuptools before invoking setup.py, to enable projects that directly\012#   import from `distutils.core` to work with newer packaging standards.\012# - It provides a clear error message when setuptools is not installed.\012# - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so\012#   setuptools doesn't think the script is `-c`. This avoids the following warning:\012#     manifest_maker: standard file '-c' not found".\012# - It generates a shim setup.py, for handling setup.cfg-only projects.\012import os, sys, tokenize\012\012try:\012    import setuptools\012except ImportError as error:\012    print(\012        "ERROR: Can not execute `setup.py` since setuptools is not available in "\012        "the build environment.",\012        file=sys.stderr,\012    )\012    sys.exit(1)\012\012__file__ = %r\012sys.argv[0] = __file__\012\012if os.path.exists(__file__):\012    filename = __file__\012    with tokenize.open(__file__) as f:\012        setup_py_code = f.read()\012else:\012    filename = "<auto-generated setuptools caller>"\012    setup_py_code = "from setuptools import setup; setup()"\012\012exec(compile(setup_py_code, filename, "exec"))\012''' % ('/app/jfly-package/setup.py',), "<pip-setuptools-caller>", "exec")) clean --all
              |       `-pstree,100 -alps
              `-python3,85 -m pip install --verbose --upgrade --require-hashes --no-deps --exists-action=i -r /tmp/pipenv-g3j6zuvm-requirements/pipenv-47gy16lx-requirement.txt -i https://pypi.org/simple
    ```

(it’s not super clear from the output here: pid 98 is executing a setup.py while pid 85 is upgrading setuptools at the same time)

If I add the --sequential flag to pipenv install, things reliably work (I let it succeed 18 times in a row before interrupting it).

NOTE: This commented out code looks very relevant: https://github.com/pypa/pipenv/blob/d378b9f91c811c95069cda9369465aae11bf67a4/pipenv/core.py#L835-L840. Or I’m seeing everything in the context of this one bug…

Notes from my investigation into why pipenv is exiting 0 when this happens.

I confirmed that the `python3 -m pip install ...` command truly is exiting 0, so this doesn’t feel like a pipenv bug.

Captured stdout from that pip install process (hack on `/usr/local/lib/python3.8/dist-packages/pipenv/core.py::_cleanup_procs` to get this):

    Using pip 22.0.4 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)
    Processing ./jfly-package
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Building wheels for collected packages: jfly
      Building wheel for jfly (setup.py): started
      Building wheel for jfly (setup.py): finished with status 'error'
      Running setup.py clean for jfly
    Failed to build jfly
    Installing collected packages: jfly
      Running setup.py install for jfly: started
      Running setup.py install for jfly: finished with status 'done'
    Successfully installed jfly
       Running command python setup.py egg_info
      running egg_info
      creating /tmp/pip-pip-egg-info-bacqy3ei/jfly.egg-info
      writing /tmp/pip-pip-egg-info-bacqy3ei/jfly.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-bacqy3ei/jfly.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-pip-egg-info-bacqy3ei/jfly.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-bacqy3ei/jfly.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-pip-egg-info-bacqy3ei/jfly.egg-info/SOURCES.txt'
      writing manifest file '/tmp/pip-pip-egg-info-bacqy3ei/jfly.egg-info/SOURCES.txt'
      Running command python setup.py bdist_wheel
      running bdist_wheel
      running build
      running build_py
      warning: build_py: byte-compiling is disabled, skipping.

And some of stderr:

      Running command python setup.py bdist_wheel
      running bdist_wheel
      running build
      running build_py
      warning: build_py: byte-compiling is disabled, skipping.

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/app/jfly-package/setup.py", line 27, in <module>
          raise e
        File "/app/jfly-package/setup.py", line 14, in <module>
          setuptools.setup(
        File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 144, in setup
          return cmd
        File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 225, in run
          install = self.reinitialize_command('install',
        File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 198, in reinitialize_command
        File "/usr/lib/python3.8/distutils/cmd.py", line 305, in reinitialize_command
          return self.distribution.reinitialize_command(command,
        File "/usr/lib/python3.8/distutils/dist.py", line 938, in reinitialize_command
          command = self.get_command_obj(command_name)
        File "/usr/lib/python3.8/distutils/dist.py", line 857, in get_command_obj
          klass = self.get_command_class(command)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 834, in get_command_class
        File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2445, in load
          def load(self, require=True, *args, **kwargs):
        File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
          "Parameters to load are deprecated.  Call .resolve and "
      ModuleNotFoundError: No module named 'setuptools.command.install'
      error: subprocess-exited-with-error

      × python setup.py bdist_wheel did not run successfully.
      │ exit code: 1
      ╰─> See above for output.

    ...

      DEPRECATION: jfly was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible replacement is to fix the wheel build issue reported above. Discussion can be found at https://github.com/pypa/pip/issues/8368
    (Note, we have pip 22.0.4 installed in the container, but pipenv has a vendored pip 21 that it looks like we’re using ([here’s a pipenv discussion about updating that vendored pip version](https://github.com/pypa/pipenv/issues/4967#issuecomment-1049927831)))

So here’s what I think happened:

- We tried to do a `setup.py bdist_wheel`. That failed with weird import errors because there was another pip install going at the same time that was upgrading setuptools.
- We fell back to doing a `setup.py install` ([relevant vendored pip code in pipenv](https://github.com/pypa/pipenv/blob/v2022.3.28/pipenv/patched/notpip/_internal/commands/install.py#L364-L369)). This succeeded, but installed stuff to /usr/lib/python3.8/site-packages rather than /usr/lib/python3.8/dist-packages!


Notes on how ubuntu distributed python is weird and expects to find and install stuff in dist-packages rather than site-packages:

- SO thread on this: https://stackoverflow.com/questions/9387928/whats-the-difference-between-dist-packages-and-site-packages

    $ docker run -it ubuntu:20
    ...
    $ python3 -c 'import sys; print(sys.path)'
    ['', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']
- I think that apt-installed `python3-distutils` provides a setup.py install that gets stuff installed to the dist-packages folder, and an updated distutils (as a consequence of upgrading setuptools) doesn’t have that logic?
- I’m unclear on how python and pip are aware to install stuff to dist-packages rather than site-packages normally…?

Now that I understand stuff, here are the workarounds I’m most in favor of:

- Do something clever to install the "right" version of setuptools to ensure that pipenv won’t try to upgrade setuptools
- Disable pipenv install parallelism (`pipenv install --sequential ...`)
- Hand wavy: understand why legacy setup.py install is installing to site-packages rather than dist-packages, and configure it correctly

I’m unclear on how useful it will be to report this upstream. Some things I could see changing for the better:

Get this pipenv code uncommented, I think it would have addressed (papered over?) this issue: https://github.com/pypa/pipenv/blob/d378b9f91c811c95069cda9369465aae11bf67a4/pipenv/core.py#L835-L840

Get pipenv vendoring a newer version of pip that no longer has the legacy fallback to setup.py install . See [relevant pipenv discussion](https://github.com/pypa/pipenv/issues/4967#issuecomment-1049927831), and relevant [pip issue](https://github.com/pypa/pip/issues/8368).

Relevant-ish thread on pipenv’s github: https://github.com/pypa/pipenv/issues/2364 . There's some interesting discussion about if pipenv even should be able to mess with stuff like pip and setuptools. I haven’t read the whole thread yet, but I wonder if at one point in time, pipenv would refuse to lock and install setuptools, and if that has since changed?
